<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJFj1Mg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJFj1Mg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHJFj1Mg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHJFj1Mg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHJFj1Mg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HJFj1Mg',
    'container.build_id' => '1a7fb7c4',
    'container.build_time' => 1740500113,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJFj1Mg');
