<?php

namespace ContainerIhGMjD9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OBE59nHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OBE59nH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OBE59nH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController::editUsers' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminReclamationController::delete' => ['privates', '.service_locator.EfDsDhC', 'get_ServiceLocator_EfDsDhCService', true],
            'App\\Controller\\AdminReclamationController::edit' => ['privates', '.service_locator.EfDsDhC', 'get_ServiceLocator_EfDsDhCService', true],
            'App\\Controller\\AdminReclamationController::index' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\AdminReclamationController::show' => ['privates', '.service_locator.SY0zWOw', 'get_ServiceLocator_SY0zWOwService', true],
            'App\\Controller\\LoginContController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\SignupController::signup' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SignupController::signupPar' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addEnseignant' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addMedecin' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addParent' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController:editUsers' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminReclamationController:delete' => ['privates', '.service_locator.EfDsDhC', 'get_ServiceLocator_EfDsDhCService', true],
            'App\\Controller\\AdminReclamationController:edit' => ['privates', '.service_locator.EfDsDhC', 'get_ServiceLocator_EfDsDhCService', true],
            'App\\Controller\\AdminReclamationController:index' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\AdminReclamationController:show' => ['privates', '.service_locator.SY0zWOw', 'get_ServiceLocator_SY0zWOwService', true],
            'App\\Controller\\LoginContController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.PqWloHb', 'get_ServiceLocator_PqWloHbService', true],
            'App\\Controller\\SignupController:signup' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SignupController:signupPar' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addEnseignant' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addMedecin' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addParent' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::admin' => '?',
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::editUsers' => '?',
            'App\\Controller\\AdminReclamationController::delete' => '?',
            'App\\Controller\\AdminReclamationController::edit' => '?',
            'App\\Controller\\AdminReclamationController::index' => '?',
            'App\\Controller\\AdminReclamationController::show' => '?',
            'App\\Controller\\LoginContController::login' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Controller\\SignupController::signup' => '?',
            'App\\Controller\\SignupController::signupPar' => '?',
            'App\\Controller\\UserController::addEnseignant' => '?',
            'App\\Controller\\UserController::addMedecin' => '?',
            'App\\Controller\\UserController::addParent' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:admin' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:editUsers' => '?',
            'App\\Controller\\AdminReclamationController:delete' => '?',
            'App\\Controller\\AdminReclamationController:edit' => '?',
            'App\\Controller\\AdminReclamationController:index' => '?',
            'App\\Controller\\AdminReclamationController:show' => '?',
            'App\\Controller\\LoginContController:login' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'App\\Controller\\SignupController:signup' => '?',
            'App\\Controller\\SignupController:signupPar' => '?',
            'App\\Controller\\UserController:addEnseignant' => '?',
            'App\\Controller\\UserController:addMedecin' => '?',
            'App\\Controller\\UserController:addParent' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
