<?php

namespace ContainerLHjLqRb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kh68C1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kh68_C1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kh68_C1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController::editUsers' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginContController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SignupController::signup' => ['privates', '.service_locator.dziv6uF', 'get_ServiceLocator_Dziv6uFService', true],
            'App\\Controller\\SignupController::signupPar' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SignupController::verifyEmail' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\UserController::addEnseignant' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addMedecin' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addParent' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\AdminController:editUsers' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginContController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SignupController:signup' => ['privates', '.service_locator.dziv6uF', 'get_ServiceLocator_Dziv6uFService', true],
            'App\\Controller\\SignupController:signupPar' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SignupController:verifyEmail' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\UserController:addEnseignant' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addMedecin' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addParent' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::admin' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::editUsers' => '?',
            'App\\Controller\\LoginContController::login' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SignupController::signup' => '?',
            'App\\Controller\\SignupController::signupPar' => '?',
            'App\\Controller\\SignupController::verifyEmail' => '?',
            'App\\Controller\\UserController::addEnseignant' => '?',
            'App\\Controller\\UserController::addMedecin' => '?',
            'App\\Controller\\UserController::addParent' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:admin' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:editUsers' => '?',
            'App\\Controller\\LoginContController:login' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SignupController:signup' => '?',
            'App\\Controller\\SignupController:signupPar' => '?',
            'App\\Controller\\SignupController:verifyEmail' => '?',
            'App\\Controller\\UserController:addEnseignant' => '?',
            'App\\Controller\\UserController:addMedecin' => '?',
            'App\\Controller\\UserController:addParent' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
