<?php

namespace ContainerQcSReXq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormMedTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormMedType' shared autowired service.
     *
     * @return \App\Form\FormMedType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormMedType.php';

        return $container->privates['App\\Form\\FormMedType'] = new \App\Form\FormMedType();
    }
}
