<?php

namespace ContainerY0JamuC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9NAVfdrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9NAVfdr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9NAVfdr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reclamation' => ['privates', '.errored..service_locator.9NAVfdr.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.9NAVfdr": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reclamation' => 'App\\Entity\\Reclamation',
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
        ]);
    }
}
