<?php

namespace ContainerY0JamuC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WXsvx99Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wXsvx99' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wXsvx99'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badWordsFilter' => ['privates', 'App\\Service\\BadWordsFilter', 'getBadWordsFilterService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
        ], [
            'badWordsFilter' => 'App\\Service\\BadWordsFilter',
            'paginator' => '?',
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
        ]);
    }
}
