<?php

namespace ContainerHJFj1Mg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormEnsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormEnsType' shared autowired service.
     *
     * @return \App\Form\FormEnsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormEnsType.php';

        return $container->privates['App\\Form\\FormEnsType'] = new \App\Form\FormEnsType();
    }
}
