<?php

namespace ContainerP7Af096;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LHS823dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lHS823d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lHS823d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badWordsFilter' => ['privates', 'App\\Service\\BadWordsFilter', 'getBadWordsFilterService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'badWordsFilter' => 'App\\Service\\BadWordsFilter',
            'entityManager' => '?',
            'paginator' => '?',
        ]);
    }
}
