<?php

namespace ContainerP7Af096;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J5BianAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j5BianA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j5BianA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'reclamation' => ['privates', '.errored..service_locator.j5BianA.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.j5BianA": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
            'reclamation' => 'App\\Entity\\Reclamation',
        ]);
    }
}
