<?php

namespace ContainerP7Af096;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9NAVfdr.App\Entity\Reclamation' shared service.
     *
     * @return \App\Entity\Reclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9NAVfdr": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".');
    }
}
