<?php

namespace ContainerFXxU6HR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MG9LekrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mG9Lekr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mG9Lekr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController::edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Controller\\BlogController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogsController::index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Controller\\DetailsBlogController::index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController:edit' => ['privates', '.service_locator.wVePTfL', 'get_ServiceLocator_WVePTfLService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Controller\\BlogController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogsController:index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'App\\Controller\\DetailsBlogController:index' => ['privates', '.service_locator.5YMAFtt', 'get_ServiceLocator_5YMAFttService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::edit' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::new' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Controller\\BlogsController::index' => '?',
            'App\\Controller\\DetailsBlogController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:edit' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:new' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'App\\Controller\\BlogsController:index' => '?',
            'App\\Controller\\DetailsBlogController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
