parameters:
    hf_api_key: '%env(HF_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Makes all classes in the src/ folder available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
            - '../src/Repository/ServiceEntityRepository.php'
            - '../src/Repository/Abstract/'


    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Define your FreeAiQuizService explicitly
    App\Service\FreeAiQuizService:
        arguments:
            $hfApiKey: '%hf_api_key%'
