<?php

namespace ContainerVagbLjS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormParTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormParType' shared autowired service.
     *
     * @return \App\Form\FormParType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormParType.php';

        return $container->privates['App\\Form\\FormParType'] = new \App\Form\FormParType();
    }
}
