<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpEjBtx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpEjBtx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpEjBtx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpEjBtx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFpEjBtx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FpEjBtx',
    'container.build_id' => '027e755a',
    'container.build_time' => 1740948788,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpEjBtx');
