<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgzeu5J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgzeu5J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWgzeu5J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWgzeu5J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWgzeu5J\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wgzeu5J',
    'container.build_id' => 'd05ac78e',
    'container.build_time' => 1739288882,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgzeu5J');
