<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerIPDa1Sl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPDa1Sl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPDa1Sl.legacy');
=======
if (\class_exists(\ContainerY0JamuC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY0JamuC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY0JamuC.legacy');
>>>>>>> 50bad6b7 (projet)

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerIPDa1Sl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIPDa1Sl\App_KernelDevDebugContainer([
    'container.build_hash' => 'IPDa1Sl',
    'container.build_id' => '5fde41a7',
    'container.build_time' => 1739747401,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPDa1Sl');
=======
    \class_alias(\ContainerY0JamuC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY0JamuC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y0JamuC',
    'container.build_id' => '099fe417',
    'container.build_time' => 1740926183,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY0JamuC');
>>>>>>> 50bad6b7 (projet)
