<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'courses' => [[], ['_controller' => 'App\\Controller\\CoursesController::admin'], [], [['text', '/courses']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'app_de' => [[], ['_controller' => 'App\\Controller\\DetailsController::det'], [], [['text', '/det']], [], [], []],
    'quiz' => [['matiere', 'userId'], ['_controller' => 'App\\Controller\\Quiz\\QuizController::index'], [], [['variable', '/', '[^/]++', 'userId', true], ['variable', '/', '[^/]++', 'matiere', true], ['text', '/quiz']], [], [], []],
    'quiz_generate_matiere_ajax' => [['matiere'], ['_controller' => 'App\\Controller\\Quiz\\QuizGeneratorController::generateQuizzes'], [], [['variable', '/', '[^/]++', 'matiere', true], ['text', '/generate-quizzes']], [], [], []],
    'questions_quiz' => [['quizId'], ['_controller' => 'App\\Controller\\Quiz\\QuizQuestionController::index'], [], [['variable', '/', '[^/]++', 'quizId', true], ['text', '/quizQuestion']], [], [], []],
    'save_quiz_submission' => [[], ['_controller' => 'App\\Controller\\Quiz\\QuizSubmissionController::saveSubmission'], [], [['text', '/save-quiz-submission']], [], [], []],
    'quiz_wait' => [['userId'], ['_controller' => 'App\\Controller\\Quiz\\QuizWaitController::waitPage'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/quiz-wait']], [], [], []],
    'allQuiz' => [[], ['_controller' => 'App\\Controller\\Quiz\\QuizWelcomeController::allQuiz'], [], [['text', '/AllQuiz']], [], [], []],
    'app_signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
    'App\Controller\AdminController::admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'App\Controller\CoursesController::admin' => [[], ['_controller' => 'App\\Controller\\CoursesController::admin'], [], [['text', '/courses']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\DetailsController::det' => [[], ['_controller' => 'App\\Controller\\DetailsController::det'], [], [['text', '/det']], [], [], []],
    'App\Controller\Quiz\QuizController::index' => [['matiere', 'userId'], ['_controller' => 'App\\Controller\\Quiz\\QuizController::index'], [], [['variable', '/', '[^/]++', 'userId', true], ['variable', '/', '[^/]++', 'matiere', true], ['text', '/quiz']], [], [], []],
    'App\Controller\Quiz\QuizGeneratorController::generateQuizzes' => [['matiere'], ['_controller' => 'App\\Controller\\Quiz\\QuizGeneratorController::generateQuizzes'], [], [['variable', '/', '[^/]++', 'matiere', true], ['text', '/generate-quizzes']], [], [], []],
    'App\Controller\Quiz\QuizQuestionController::index' => [['quizId'], ['_controller' => 'App\\Controller\\Quiz\\QuizQuestionController::index'], [], [['variable', '/', '[^/]++', 'quizId', true], ['text', '/quizQuestion']], [], [], []],
    'App\Controller\Quiz\QuizSubmissionController::saveSubmission' => [[], ['_controller' => 'App\\Controller\\Quiz\\QuizSubmissionController::saveSubmission'], [], [['text', '/save-quiz-submission']], [], [], []],
    'App\Controller\Quiz\QuizWaitController::waitPage' => [['userId'], ['_controller' => 'App\\Controller\\Quiz\\QuizWaitController::waitPage'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/quiz-wait']], [], [], []],
    'App\Controller\Quiz\QuizWelcomeController::allQuiz' => [[], ['_controller' => 'App\\Controller\\Quiz\\QuizWelcomeController::allQuiz'], [], [['text', '/AllQuiz']], [], [], []],
    'App\Controller\SignupController::signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
];
