<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'app_signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
    'App\Controller\AdminController::admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\SignupController::signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
];
