<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'app_blog_index' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/in']], [], [], []],
    'app_blog_new' => [[], ['_controller' => 'App\\Controller\\BlogController::new'], [], [['text', '/new']], [], [], []],
    'app_blog_show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'app_blog_edit' => [['id'], ['_controller' => 'App\\Controller\\BlogController::edit'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true]], [], [], []],
    'app_blog_delete' => [['id'], ['_controller' => 'App\\Controller\\BlogController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'app_blogs' => [[], ['_controller' => 'App\\Controller\\BlogsController::index'], [], [['text', '/blogsUser']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'app_details_blog' => [['id'], ['_controller' => 'App\\Controller\\DetailsBlogController::index'], [], [['variable', '', '[^/]++', 'id', true], ['text', '/details_blog']], [], [], []],
    'app_signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
    'App\Controller\AdminController::admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'App\Controller\BlogController::index' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/in']], [], [], []],
    'App\Controller\BlogController::new' => [[], ['_controller' => 'App\\Controller\\BlogController::new'], [], [['text', '/new']], [], [], []],
    'App\Controller\BlogController::show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'App\Controller\BlogController::edit' => [['id'], ['_controller' => 'App\\Controller\\BlogController::edit'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true]], [], [], []],
    'App\Controller\BlogController::delete' => [['id'], ['_controller' => 'App\\Controller\\BlogController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'App\Controller\BlogsController::index' => [[], ['_controller' => 'App\\Controller\\BlogsController::index'], [], [['text', '/blogsUser']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\DetailsBlogController::index' => [['id'], ['_controller' => 'App\\Controller\\DetailsBlogController::index'], [], [['variable', '', '[^/]++', 'id', true], ['text', '/details_blog']], [], [], []],
    'App\Controller\SignupController::signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
];
